name: End-to-end tests
'on':
  - push
jobs:
  All_Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
  Single_test: null
  runs-on: ubuntu-22.04
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0
    - name: Install dependencies
      run: npm install
    - name: Run smoke script
      run: 'npm run cypress:run_spec'
